version: '3'
services:

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/log:/log/nginx/

  application:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile-application
    expose:
      - 8083
    ports:
      - 8083:8080
    environment:
      - TZ=Asia/Seoul
